// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFY5fTD0j0eaXqHDCfb7ua6Z2qov-J1Bw',
    appId: '1:535581126744:android:78248437d2f46bd8dd9a2d',
    messagingSenderId: '535581126744',
    projectId: 'fir-notification-a9f76',
    storageBucket: 'fir-notification-a9f76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOoiI0crHJ6_y26PQr3Iwv5Z9HWAjImB4',
    appId: '1:535581126744:ios:baeb5a7419f4db96dd9a2d',
    messagingSenderId: '535581126744',
    projectId: 'fir-notification-a9f76',
    storageBucket: 'fir-notification-a9f76.appspot.com',
    iosClientId: '535581126744-q4j4ocia7vadbjjrg3913p115m1mrb47.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOoiI0crHJ6_y26PQr3Iwv5Z9HWAjImB4',
    appId: '1:535581126744:ios:6bfa3e4440692cebdd9a2d',
    messagingSenderId: '535581126744',
    projectId: 'fir-notification-a9f76',
    storageBucket: 'fir-notification-a9f76.appspot.com',
    iosClientId: '535581126744-t4hnrahiu4q97p6c5uge62gfc0q2ouj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotification.RunnerTests',
  );
}
